services:
  tabdash-extension:
    restart: always
    build:
      context: ./extension
      dockerfile: ./Dockerfile
      args:
        VITE_OPENWEATHER_API_KEY: ${WEATHER_API_KEY}
        VITE_UNSPLASH_API_KEY: ${UNSPLASH_API_KEY}
        VITE_COMPANION_BASE: ${VITE_COMPANION_BASE:-https://tabdash.wesley.fyi}
        VITE_BACKEND_BASE: ${VITE_BACKEND_BASE:-https://tabdash.wesley.fyi/api}
        VITE_IS_EXTENSION: 'false'
    environment:
      - VITE_COMPANION_BASE=https://tabdash.wesley.fyi
      - VITE_BACKEND_BASE=https://tabdash.wesley.fyi/api
      - VITE_IS_EXTENSION=false
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tabdashextension.rule=Host(`online.tabdash.wesley.fyi`)'
      - 'traefik.http.routers.tabdashextension.entrypoints=websecure'
      - 'traefik.http.routers.tabdashextension.tls.certresolver=letsencrypt'
      - 'traefik.http.services.tabdashextension.loadbalancer.server.port=3003'
    networks:
      - dokploy-network

  tabdash-companion:
    restart: always
    build:
      context: ./companion
      dockerfile: ./Dockerfile
      args:
        PUBLIC_BACKEND_BASE: ${PUBLIC_BACKEND_BASE:-https://tabdash.wesley.fyi/api}
        PUBLIC_ONLINE_BASE: ${PUBLIC_ONLINE_BASE:-https://online.tabdash.wesley.fyi}
    environment:
      - PUBLIC_BACKEND_BASE=https://tabdash.wesley.fyi/api
      - PUBLIC_ONLINE_BASE=https://online.tabdash.wesley.fyi
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tabdashcompanion.rule=Host(`tabdash.wesley.fyi`)'
      - 'traefik.http.routers.tabdashcompanion.priority=10'
      - 'traefik.http.routers.tabdashcompanion.entrypoints=websecure'
      - 'traefik.http.routers.tabdashcompanion.tls.certresolver=letsencrypt'
      - 'traefik.http.services.tabdashcompanion.loadbalancer.server.port=3000'
    networks:
      - dokploy-network

  tabdash-backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - PORT=3005
      - DB_PATH=/opt/TabDash-data
    volumes:
      - tabdash-backend-data:/opt/TabDash-data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tabdashbackend.rule=(Host(`tabdash.wesley.fyi`) && PathPrefix(`/api`)) || Host(`tabdashbe.wesley.fyi`)'
      - 'traefik.http.routers.tabdashbackend.priority=100'
      - 'traefik.http.routers.tabdashbackend.entrypoints=websecure'
      - 'traefik.http.routers.tabdashbackend.tls.certresolver=letsencrypt'
      - 'traefik.http.services.tabdashbackend.loadbalancer.server.port=3005'
    networks:
      - dokploy-network

volumes:
  tabdash-backend-data:
    name: tabdash-backend-data

networks:
  dokploy-network:
    external: true
