version: '3'

services:
  tabdash-extension:
    restart: always
    build:
      context: ./extension
      dockerfile: ./Dockerfile
      args:
        VITE_OPENWEATHER_API_KEY: ${WEATHER_API_KEY}
        VITE_UNSPLASH_API_KEY: ${UNSPLASH_API_KEY}
    environment:
      - VITE_COMPANION_BASE=https://tabdash.wesley.fyi
      - VITE_BACKEND_BASE=https://tabdashbe.wesley.fyi
      - VITE_IS_EXTENSION=false
    ports:
      - '3003:3003'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tabdashextension.rule=Host(`online.tabdash.wesley.fyi`)"
      - "traefik.http.routers.tabdashextension.entrypoints=websecure"
      - "traefik.http.routers.tabdashextension.tls.certresolver=le"
    networks:
      - traefik_default

  tabdash-companion:
    restart: always
    build:
      context: ./companion
      dockerfile: ./Dockerfile
    environment:
      - PUBLIC_BACKEND_BASE=https://tabdashbe.wesley.fyi
    ports:
      - '3000:3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tabdashcompanion.rule=Host(`tabdash.wesley.fyi`)"
      - "traefik.http.routers.tabdashcompanion.entrypoints=websecure"
      - "traefik.http.routers.tabdashcompanion.tls.certresolver=le"
    networks:
      - traefik_default

  tabdash-backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - PORT=3005
      - DB_PATH=/opt/TabDash-data
    ports:
      - '3005:3005'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tabdashcompanion.rule=Host(`tabdashbe.wesley.fyi`)"
      - "traefik.http.routers.tabdashcompanion.entrypoints=websecure"
      - "traefik.http.routers.tabdashcompanion.tls.certresolver=le"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
