/**
 * Builds an ordered list of candidate icon URLs for a given shortcut link.
 * The list goes from highest-quality to guaranteed-available, so callers can
 * walk through it on `onError` until an image loads successfully.
 *
 * Order (direct-from-site first, aggregators last):
 *  1. Configured icon (if already set by the user and not auto-generated)
 *  2. Apple Touch Icon at site root  (usually 180×180, high-res)
 *  3. Apple Touch Icon (precomposed variant for older sites)
 *  4. Direct /favicon.ico           (the site's own icon, incl. self-hosted apps)
 *  5. Unavatar aggregator (`fallback=false` so a miss 404s instead of
 *     returning a low-res letter avatar and blocking the waterfall)
 *
 * Notes:
 * - Page-declared icons (`<link rel="icon">`, e.g. `/logo.svg`) are resolved
 *   live by `ShortcutIcon` via `fetchSiteIcons` and prepended to this list.
 * - The Google favicon service is deliberately NOT in the chain: it answers
 *   200 with a generic 16px globe on miss, which renders as a blurry tile
 *   and shadows the letter-avatar fallback.
 *
 * All entries are plain `<img>`-loadable URLs, so no CORS/host permissions
 * are needed for the waterfall itself. Misses (e.g. unavatar 404s for
 * self-hosted hosts) are expected and harmless: the browser logs them while
 * the waterfall moves on. The caller renders the final letter-avatar
 * fallback when every candidate fails.
 */
export const buildIconCandidates = (link: string, configuredIcon?: string): string[] => {
  let origin = '',
    hostname = '';
  try {
    const url = new URL(link);
    origin = url.origin; // E.g. "https://github.com"
    hostname = url.hostname; // E.g. "github.com"
  } catch {
    // Unparseable URL – return only the configured icon (if any)
    return configuredIcon ? [configuredIcon] : [];
  }

  const candidates: string[] = [];

  if (configuredIcon && !isAutoGeneratedIcon(configuredIcon, link)) {
    candidates.push(configuredIcon);
  }

  // High-res Apple Touch Icons served directly by the site (usually 180×180 PNG)
  candidates.push(`${origin}/apple-touch-icon.png`, `${origin}/apple-touch-icon-precomposed.png`);

  // The site's own classic favicon – works for self-hosted apps too
  candidates.push(`${origin}/favicon.ico`);

  // Unavatar – smart aggregator; fallback=false lets the waterfall continue
  // To the letter-avatar fallback instead of a low-res letter image.
  candidates.push(`https://unavatar.io/${hostname}?fallback=false`);

  return candidates;
};

/**
 * True when a stored icon looks like a previously auto-resolved value
 * (Google service at any size, unavatar, or a same-origin apple/favicon path)
 * rather than a user-supplied custom URL. Auto values are rebuilt fresh so
 * old low-res entries (e.g. Google `size=128`) self-heal to high-res.
 */
export const isAutoGeneratedIcon = (icon: string, link: string): boolean => {
  if (!icon) {
    return true;
  }
  if (icon.startsWith('data:')) {
    return false;
  }
  let iconUrl: URL | null = null,
    linkUrl: URL | null = null;
  try {
    iconUrl = new URL(icon);
  } catch {
    return false;
  }
  try {
    linkUrl = new URL(link);
  } catch {
    linkUrl = null;
  }
  const host = iconUrl.hostname;
  if (host === 't0.gstatic.com' || host.endsWith('.gstatic.com')) {
    return true;
  }
  if (host === 'unavatar.io' || host === 'icons.duckduckgo.com') {
    return true;
  }
  if (linkUrl && iconUrl.origin === linkUrl.origin) {
    const path = iconUrl.pathname.toLowerCase();
    if (path.includes('apple-touch-icon') || path.includes('favicon')) {
      return true;
    }
  }
  return false;
};

/** Icons smaller than this (in natural pixels) are treated as a miss and
 * skipped – upscaling them would only produce a blurry tile. Vector (SVG)
 * sources are exempt since they scale losslessly. */
export const MIN_ICON_SIZE = 64;

/** True when a loaded raster icon is too small to display without blur. */
export const shouldRejectIcon = (
  src: string,
  naturalWidth: number,
  naturalHeight: number,
): boolean => {
  if (/\.svg(\?|#|$)/i.test(src) || src.startsWith('data:image/svg')) {
    return false;
  }
  return naturalWidth < MIN_ICON_SIZE || naturalHeight < MIN_ICON_SIZE;
};

/** Extracts the domain hostname from a URL string, or null on failure. */
export const extractHostname = (link: string): string | null => {
  try {
    return new URL(link).hostname;
  } catch {
    return null;
  }
};
