import { describe, expect, it } from 'bun:test';
import { buildIconCandidates, isAutoGeneratedIcon, shouldRejectIcon } from './favicon.js';

describe('buildIconCandidates', () => {
  it('tries direct site icons before aggregators, no generic-globe service', () => {
    const candidates = buildIconCandidates('https://nest.w4y.io');
    expect(candidates).toEqual([
      'https://nest.w4y.io/apple-touch-icon.png',
      'https://nest.w4y.io/apple-touch-icon-precomposed.png',
      'https://nest.w4y.io/favicon.ico',
      'https://unavatar.io/nest.w4y.io?fallback=false',
    ]);
  });

  it('keeps custom icons first', () => {
    const candidates = buildIconCandidates('https://nest.w4y.io', 'https://nest.w4y.io/logo.png');
    expect(candidates[0]).toBe('https://nest.w4y.io/logo.png');
  });

  it('rebuilds legacy auto icons instead of pinning them', () => {
    const legacy =
        'https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://nest.w4y.io&size=128',
      candidates = buildIconCandidates('https://nest.w4y.io', legacy);
    expect(candidates).not.toContain(legacy);
    expect(candidates[0]).toBe('https://nest.w4y.io/apple-touch-icon.png');
  });

  it('returns only the configured icon for unparseable links', () => {
    expect(buildIconCandidates('not a url')).toEqual([]);
    expect(buildIconCandidates('not a url', 'https://example.com/i.png')).toEqual([
      'https://example.com/i.png',
    ]);
  });
});

describe('shouldRejectIcon', () => {
  it('rejects tiny raster icons (e.g. the generic 16px globe)', () => {
    expect(shouldRejectIcon('https://example.com/f.png', 16, 16)).toBe(true);
    expect(shouldRejectIcon('https://example.com/f.png', 32, 32)).toBe(true);
    expect(shouldRejectIcon('https://example.com/f.png', 180, 180)).toBe(false);
    expect(shouldRejectIcon('https://example.com/f.png', 64, 64)).toBe(false);
  });

  it('exempts vector sources regardless of reported size', () => {
    expect(shouldRejectIcon('https://nest.w4y.io/logo.svg', 16, 16)).toBe(false);
    expect(shouldRejectIcon('data:image/svg+xml;base64,abc', 0, 0)).toBe(false);
  });
});

describe('isAutoGeneratedIcon', () => {
  it('detects service-generated icons', () => {
    expect(
      isAutoGeneratedIcon('https://t0.gstatic.com/faviconV2?x=1&size=128', 'https://nest.w4y.io'),
    ).toBe(true);
    expect(isAutoGeneratedIcon('https://unavatar.io/nest.w4y.io', 'https://nest.w4y.io')).toBe(
      true,
    );
  });

  it('keeps user icons', () => {
    expect(isAutoGeneratedIcon('data:image/png;base64,abc', 'https://nest.w4y.io')).toBe(false);
    expect(isAutoGeneratedIcon('https://nest.w4y.io/logo.png', 'https://nest.w4y.io')).toBe(false);
    expect(isAutoGeneratedIcon('https://cdn.example.com/a.png', 'https://nest.w4y.io')).toBe(false);
  });
});
