import { Show, createEffect, createMemo, createSignal } from 'solid-js';
import type { Component } from 'solid-js';
import { buildIconCandidates, shouldRejectIcon } from '../../api/favicon.js';
import { fetchSiteIcons } from '../../api/siteIcon.js';

export interface ShortcutIconProps {
  link: string;
  name: string;
  configuredIcon?: string;
  size: number;
}

/**
 * High-res shortcut icon with an automatic fallback waterfall.
 * Page-declared icons (`<link rel="icon">`, resolved live) come first,
 * then the static chain from `buildIconCandidates`, ending in a
 * hostname-colored letter avatar. Auto-generated legacy icons
 * (Google size=128, etc.) are rebuilt fresh via `isAutoGeneratedIcon`.
 * The candidate list freezes once an image loads, so late-arriving
 * discoveries never swap a working icon (no flicker).
 */
export const ShortcutIcon: Component<ShortcutIconProps> = (props) => {
  const staticCandidates = createMemo(() => buildIconCandidates(props.link, props.configuredIcon)),
    [discovered, setDiscovered] = createSignal<string[]>([]),
    [frozen, setFrozen] = createSignal<string[] | undefined>(),
    [index, setIndex] = createSignal(0),
    candidates = createMemo(() => frozen() ?? [...discovered(), ...staticCandidates()]);

  createEffect(() => {
    // Reset the waterfall whenever the link or stored icon changes and
    // Resolve page-declared icons in parallel (cached per origin).
    // StaticCandidates() already tracks link + configuredIcon, so this
    // Re-runs whenever either changes.
    const { link } = props;
    staticCandidates();
    setFrozen(undefined);
    setDiscovered([]);
    setIndex(0);
    void fetchSiteIcons(link).then((urls) => {
      if (props.link !== link || urls.length === 0) {
        return;
      }
      setDiscovered(urls);
      // Restart the waterfall at the better source, unless an image already
      // Loaded (frozen list) – never swap a working icon.
      if (!frozen()) {
        setIndex(0);
      }
    });
  });

  const src = () => candidates()[index()],
    exhausted = () => index() >= candidates().length,
    letter = () => (props.name.trim().charAt(0) || '?').toUpperCase(),
    // Deterministic tile color from the hostname, so self-hosted apps without
    // any fetchable icon still get a distinct, intentional-looking tile.
    hue = () => {
      let host = props.name;
      try {
        host = new URL(props.link).hostname || props.name;
      } catch {
        // Keep name as hash input
      }
      let hash = 0;
      for (let i = 0; i < host.length; i++) {
        hash = (hash * 31 + host.charCodeAt(i)) % 360;
      }
      return hash;
    };

  return (
    <Show
      when={!exhausted() && src()}
      fallback={
        <div
          class="grid place-items-center text-white font-semibold select-none"
          style={{
            background: `linear-gradient(135deg, hsl(${hue()}, 65%, 48%), hsl(${(hue() + 40) % 360}, 65%, 38%))`,
            'font-size': `${Math.round(props.size * 0.42)}px`,
            height: `${props.size}px`,
            width: `${props.size}px`,
          }}
          aria-hidden="true"
        >
          {letter()}
        </div>
      }
    >
      <img
        src={src()}
        width={props.size}
        height={props.size}
        alt={`${props.name} icon`}
        class="object-contain"
        style={{ height: `${props.size}px`, width: `${props.size}px` }}
        loading="lazy"
        referrerpolicy="no-referrer"
        onLoad={(e) => {
          const current = src(),
            img = e.currentTarget;
          // Too small to display without blur → treat as a miss and move on.
          if (
            current === undefined ||
            shouldRejectIcon(current, img.naturalWidth, img.naturalHeight)
          ) {
            setIndex((i) => i + 1);
            return;
          }
          setFrozen(candidates());
        }}
        onError={() => setIndex((i) => i + 1)}
      />
    </Show>
  );
};
