name: Deploy TabDash

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /opt/tabdash
            git clone https://github.com/ur-wesley/tabdash.git
            WEATHER_API_KEY=${{secrets.OPENWEATHER_API_KEY}} UNSPLASH_API_KEY=${{secrets.UNSPLASH_API_KEY}} docker compose up -d
